### ISSUE TITLE
d2l-pdf-viewer: Polymer 2(+?) Rendering Issues

### ISSUE THREAD

**Issue by apalaniuk** [Brightspace/d2l-file-viewer#2]
- Some, though not all, PDFs have incorrectly rendered pages, in that content is duplicated across them.
- Page centering behavior is different (in that, it doesn't). This might be a quick fix, but not immediately important since there aren't any potential consumers using Polymer 2.x (and we're moving directly to 3.x).

Mainly tracked to revisit against potential future Polymer 3.x issues.

![polymer-2-pdf-issues](https://user-images.githubusercontent.com/17710124/47377444-e770f180-d6ba-11e8-89a1-a71004d8f483.JPG)

**Comment by apalaniuk** [comment]
Issue is due to using an external stylesheet for the PDF viewer, support for which is removed in Polymer 2.

**Comment by ChrisKraljevicD2L** [comment]
Is copy-pasta of the stylesheet into a polymer custom style, or the `<style>` of `<d2l-pdf-viewer>` itself considered too gross to fix this?
